version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/smart_leads
      - JWT_SECRET=supersecretjwtkey_replace_in_prod
    depends_on:
      - mongodb
    networks:
      - mern-network

  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - mern-network

volumes:
  mongodb_data:

networks:
  mern-network:
    driver: bridge
